version: '2.1'
orbs:
  snyk: snyk/snyk@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/install
      - run:
          command: snyk version
          name: Which version of snyk is installed
      - run:
          command: snyk code test --unmanaged
          name: Run code scan
workflows: null
