
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/ronit/Desktop/MSVC/msvc/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.37.32824.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/ronit/Desktop/MSVC/msvc/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.37.32824.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-p2p3re"
      binary: "C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-p2p3re"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-p2p3re
        
        Run Build Command(s):C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_8da79\\fast && 	C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\nmake.exe  -f CMakeFiles\\cmTC_8da79.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_8da79.dir\\build
        Building C object CMakeFiles/cmTC_8da79.dir/CMakeCCompilerABI.c.obj
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_8da79.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\CMakeScratch\\TryCompile-p2p3re --filter-prefix="Note: including file: " -- C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\ronit\\AppData\\Local\\Temp\\nmEE04.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_8da79.exe
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_8da79.dir --rc=C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests -- C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_8da79.dir\\objects1.rsp @C:\\Users\\ronit\\AppData\\Local\\Temp\\nmEE73.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_8da79.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_8da79.dir/embed.manifest
        RC Pass 1:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_8da79.dir/manifest.res CMakeFiles\\cmTC_8da79.dir/manifest.rc
        LINK Pass 1:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_8da79.dir\\objects1.rsp /out:cmTC_8da79.exe /implib:cmTC_8da79.lib /pdb:C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\CMakeScratch\\TryCompile-p2p3re\\cmTC_8da79.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_8da79.dir/intermediate.manifest CMakeFiles\\cmTC_8da79.dir/manifest.res
        MT:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_8da79.dir/intermediate.manifest /out:CMakeFiles\\cmTC_8da79.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_8da79.dir/manifest.res CMakeFiles\\cmTC_8da79.dir/manifest.rc
        FINAL LINK:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_8da79.dir\\objects1.rsp /out:cmTC_8da79.exe /implib:cmTC_8da79.lib /pdb:C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\CMakeScratch\\TryCompile-p2p3re\\cmTC_8da79.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_8da79.dir/intermediate.manifest CMakeFiles\\cmTC_8da79.dir/manifest.res
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-txxxw3"
      binary: "C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-txxxw3"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/ronit/Desktop/PSEMU/PSEMU/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-txxxw3
        
        Run Build Command(s):C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_e11cb\\fast && 	C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\nmake.exe  -f CMakeFiles\\cmTC_e11cb.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_e11cb.dir\\build
        Building CXX object CMakeFiles/cmTC_e11cb.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_e11cb.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\CMakeScratch\\TryCompile-txxxw3 --filter-prefix="Note: including file: " -- C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\ronit\\AppData\\Local\\Temp\\nmF1FC.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_e11cb.exe
        	"C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_e11cb.dir --rc=C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests -- C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_e11cb.dir\\objects1.rsp @C:\\Users\\ronit\\AppData\\Local\\Temp\\nmF25A.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_e11cb.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_e11cb.dir/embed.manifest
        RC Pass 1:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_e11cb.dir/manifest.res CMakeFiles\\cmTC_e11cb.dir/manifest.rc
        LINK Pass 1:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_e11cb.dir\\objects1.rsp /out:cmTC_e11cb.exe /implib:cmTC_e11cb.lib /pdb:C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\CMakeScratch\\TryCompile-txxxw3\\cmTC_e11cb.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_e11cb.dir/intermediate.manifest CMakeFiles\\cmTC_e11cb.dir/manifest.res
        MT:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_e11cb.dir/intermediate.manifest /out:CMakeFiles\\cmTC_e11cb.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\WINDOW~1\\10\\bin\\100226~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_e11cb.dir/manifest.res CMakeFiles\\cmTC_e11cb.dir/manifest.rc
        FINAL LINK:
        C:\\Users\\ronit\\Desktop\\MSVC\\msvc\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_e11cb.dir\\objects1.rsp /out:cmTC_e11cb.exe /implib:cmTC_e11cb.lib /pdb:C:\\Users\\ronit\\Desktop\\PSEMU\\PSEMU\\cmake-build-release\\CMakeFiles\\CMakeScratch\\TryCompile-txxxw3\\cmTC_e11cb.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_e11cb.dir/intermediate.manifest CMakeFiles\\cmTC_e11cb.dir/manifest.res
        
      exitCode: 0
...
